spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: testpassword
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  redis:
    client-name: simple-redis
    host: localhost
    database: 0
    port: 6379
    password: